version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - kratos-net
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - kratos-net
  consul:
    image: consul:1.15
    container_name: consul
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - 8500:8500
    networks:
      - kratos-net
  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    networks:
      - kratos-net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - kratos-net
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - kratos-net

  kratos-bff:
    image: golang:1.21-alpine3.18
    container_name: kratos-bff
    volumes:
      - ./:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: /bin/sh -c "cd app/bff/cmd/server && go build . && ./server"
    expose:
      - 8000
      - 9000
    ports:
      - 8000:8000
    networks:
      - kratos-net
  kratos-user:
    image: golang:1.21-alpine3.18
    container_name: kratos-user
    volumes:
      - ./:/usr/src/myapp
    working_dir: /usr/src/myapp
    command: /bin/sh -c "cd app/user/cmd/server && go build . && ./server"
    expose:
      - 8000
      - 9000
    networks:
      - kratos-net

networks:
  kratos-net: